FROM python:3.8.1-slim-buster

RUN pip install --upgrade pip

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY config/profile.docker.yml /root/.dbt/profiles.yml

COPY . .

RUN chmod -R 755 scripts/

ENTRYPOINT [ "/bin/sh", "-c" ]
CMD ["scripts/run_dbt.sh"]