#GET https://id-sandbox.alfabank.ru/oidc/authorize?response_type=code&client_id=06fabd37-19e8-4d12-b13d-efde07c4b0ac&redirect_uri=http%3A%2F%2Flocalhost&scope=transactions%20openid&state=abcde HTTP/1.1
#accept: application/json

GET https://id-sandbox.alfabank.ru/oidc/authorize?response_type=code&client_id=da9661de-2d30-43e4-b478-3c80130a68e5&redirect_uri=http%3A%2F%2Flocalhost&scope=transactions%20openid&state=abcde HTTP/1.1
accept: application/json