GET https://sandbox.alfabank.ru/api/statement/transactions?accountNumber=40702810102300000001&statementDate=2018-03-15 HTTP/1.1
Accept: application/json
Authorization: Bearer eyJraWQiOiJiYWFzLWFsZmEtdGVzdC1qd3QiLCJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiIzNjRiODNjZS03NjJiLTQ3OWEtODdmNS1hZjgyYTY4NGFhZTYiLCJhdWQiOiIwNmZhYmQzNy0xOWU4LTRkMTItYjEzZC1lZmRlMDdjNGIwYWMiLCJpc3MiOiJodHRwczovL2lkLXNhbmRib3guYWxmYWJhbmsucnUvb2lkYyIsImV4cCI6MTcxMDYwNjQ5Nywic2NvcGVfc2VydmljZXMiOlsidHJhbnNhY3Rpb25zIl0sImlhdCI6MTcxMDYwMjg5NywianRpIjoiYzI1MzYwNmYtNDZjYi00ZGMyLWExZGUtZjEyNzE2OTdhOTFmIiwic2NvcGVfY2xhaW1zIjpbImV4cCIsImFjciIsImF1ZCIsIm5vbmNlIiwic3ViIiwiaXNzIiwiaWF0IiwiYXpwIiwiYXV0aF90aW1lIl19.AizDIEPSQfaxV1RxoLo5Dev6lAt2LdkoXc05-i1zMIyS1icW3GWFbqzrKCLxmM6V3BIuIK9uT7wFGpbwE3LOEZRgS52x7dw4E3j_E9yzYHFFu9xrzrC52qSwRfdC8o1SXgDxFYq9m4u-5ypdBQ2k-vnvyTtN4cp7tNryNct9AcX7bP971VztnCM2ffaSaMWPHMTlXt_s9fK6RHlIOkMAJiviw_nLegxNu28PV7qmLxj4iDnO3U89s6epFtZTIQT4C0O_PWhyqwhDHBGpAKi43tppwXGiu4eaVToBawLbgER_-8KEZgHofahPKJ7FrqnqEEjifqmif3s3B6mfxAzFqg
Content-Type: application/json