GET https://sandbox.alfabank.ru/api/statement/transactions?accountNumber=40702810102300000001&statementDate=2018-03-15 HTTP/1.1
Accept: application/json
Authorization: Bearer eyJraWQiOiJiYWFzLWFsZmEtdGVzdC1qd3QiLCJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiIzNjRiODNjZS03NjJiLTQ3OWEtODdmNS1hZjgyYTY4NGFhZTYiLCJhdWQiOiJkYTk2NjFkZS0yZDMwLTQzZTQtYjQ3OC0zYzgwMTMwYTY4ZTUiLCJpc3MiOiJodHRwczovL2lkLXNhbmRib3guYWxmYWJhbmsucnUvb2lkYyIsImV4cCI6MTcxMzM4MDI0OCwic2NvcGVfc2VydmljZXMiOlsidHJhbnNhY3Rpb25zIl0sImlhdCI6MTcxMzM3NjY0OCwianRpIjoiYTM3MzdmMTYtMGUyNS00Mzc3LTkwNTMtZjcyMTE1ZDlkZTA5Iiwic2NvcGVfY2xhaW1zIjpbImV4cCIsInN1YiIsImFjciIsImF1ZCIsIm5vbmNlIiwiYXV0aF90aW1lIiwiYXpwIiwiaXNzIiwiaWF0Il19.3isVloPtwJykP0IOwJIF0VmfkZVou0_lbt2e9G37GbdWpkswN5o000UOlCGpzHZzsbMWyziwRZsF-l7j-Z40tvndZ7tEZFtE62wCjt0CgQ3nX0arRC_dJyh6HKo6NavnIoCGD-vszAz1AgdP74xqAXXUQRsLcruJoaI3xL6TolZU64UHr4xCv5P4crfPINMJOopzdraCce6FYv8fep-eklvw7vlAVyniVXrmF4sHCIg3bl6GNv5ULgZfNrGoWuqlptFMIpqRSQ8wPTAL6HR0t__5qjQTCtdrwSdFx_v3fYNGdGZrGWatkORBPxFw7_cH5th_oGuja71INNkpKJ1QIg
Content-Type: application/json