POST https://sandbox.alfabank.ru/oidc/token HTTP/1.1
accept: application/json
#content-type: application/json
content-type: application/x-www-form-urlencoded

grant_type=refresh_token
&refresh_token=e2aa3f84-e697-41f7-aaab-256e69713c1e
&client_id=06fabd37-19e8-4d12-b13d-efde07c4b0ac
&client_secret=7#j79b2R(*F28CI3fQ8$k$02e


# {
#   "access_token": "eyJraWQiOiJiYWFzLWFsZmEtdGVzdC1qd3QiLCJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiIzNjRiODNjZS03NjJiLTQ3OWEtODdmNS1hZjgyYTY4NGFhZTYiLCJhdWQiOiIwNmZhYmQzNy0xOWU4LTRkMTItYjEzZC1lZmRlMDdjNGIwYWMiLCJpc3MiOiJodHRwczovL2lkLXNhbmRib3guYWxmYWJhbmsucnUvb2lkYyIsImV4cCI6MTcxMDYwNjQ5Nywic2NvcGVfc2VydmljZXMiOlsidHJhbnNhY3Rpb25zIl0sImlhdCI6MTcxMDYwMjg5NywianRpIjoiYzI1MzYwNmYtNDZjYi00ZGMyLWExZGUtZjEyNzE2OTdhOTFmIiwic2NvcGVfY2xhaW1zIjpbImV4cCIsImFjciIsImF1ZCIsIm5vbmNlIiwic3ViIiwiaXNzIiwiaWF0IiwiYXpwIiwiYXV0aF90aW1lIl19.AizDIEPSQfaxV1RxoLo5Dev6lAt2LdkoXc05-i1zMIyS1icW3GWFbqzrKCLxmM6V3BIuIK9uT7wFGpbwE3LOEZRgS52x7dw4E3j_E9yzYHFFu9xrzrC52qSwRfdC8o1SXgDxFYq9m4u-5ypdBQ2k-vnvyTtN4cp7tNryNct9AcX7bP971VztnCM2ffaSaMWPHMTlXt_s9fK6RHlIOkMAJiviw_nLegxNu28PV7qmLxj4iDnO3U89s6epFtZTIQT4C0O_PWhyqwhDHBGpAKi43tppwXGiu4eaVToBawLbgER_-8KEZgHofahPKJ7FrqnqEEjifqmif3s3B6mfxAzFqg",
#   "refresh_token": "2ea2dc23-b36d-468a-a058-21a91d844cdc",
#   "token_type": "Bearer",
#   "expires_in": 3600
# }

