POST https://sandbox.alfabank.ru/oidc/token HTTP/1.1
accept: application/json
#content-type: application/json
content-type: application/x-www-form-urlencoded

grant_type=authorization_code
&code=7d5832a5-7d64-4932-853a-c6831e497c93
&client_id=da9661de-2d30-43e4-b478-3c80130a68e5
&client_secret=jS$01$m*MFad8257x4EW$6*67
&redirect_uri=http%3A%2F%2Flocalhost


# grant_type=authorization_code
# &code=76d01564-217e-4b20-8ab7-4189186620a2
# &client_id=06fabd37-19e8-4d12-b13d-efde07c4b0ac
# &client_secret=7#j79b2R(*F28CI3fQ8$k$02e
# &redirect_uri=http%3A%2F%2Flocalhost



# {
#     "grant_type": "authorization_code",
#     "code": "12d06657-2c02-4053-a35a-3f53e8a0186a",
#     "client_id": "06fabd37-19e8-4d12-b13d-efde07c4b0ac",
#     "client_secret": "1C#0nB1GYnk,l#8!9yF94205&",
#     "redirect_uri": "http://localhost"    
# }


# {
#   "access_token": "eyJraWQiOiJiYWFzLWFsZmEtdGVzdC1qd3QiLCJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiIzNjRiODNjZS03NjJiLTQ3OWEtODdmNS1hZjgyYTY4NGFhZTYiLCJhdWQiOiIwNmZhYmQzNy0xOWU4LTRkMTItYjEzZC1lZmRlMDdjNGIwYWMiLCJpc3MiOiJodHRwczovL2lkLXNhbmRib3guYWxmYWJhbmsucnUvb2lkYyIsImV4cCI6MTcxMDUzODMwMSwic2NvcGVfc2VydmljZXMiOlsidHJhbnNhY3Rpb25zIl0sImlhdCI6MTcxMDUzNDcwMSwianRpIjoiYzc1NDgzZTUtMGVlMy00ODhmLWJlOTMtZjhkNjRkNWVhMmExIiwic2NvcGVfY2xhaW1zIjpbImV4cCIsImFjciIsImF1ZCIsIm5vbmNlIiwic3ViIiwiaXNzIiwiaWF0IiwiYXpwIiwiYXV0aF90aW1lIl19.pVel5p3Qm7jVc6CinwM9oMaeOyv5J4TN_2-n6erFknbHeYthWXmtrJyHeVE-UjR4PPjfd3XhRt5eYaXY3m1VzHS3wU9mp5UPhPNKhRsCWgQjJG9CSefJaKkSI88lJao6VuR_P83qReSXek5Ugy1mxK4AXl-8Dj-cq77Vkukfu3jwZ7AGuAKzpG4kulL4dLnCkQ5EJkEDv8OBRhv47tYEOtX76_HCWu5-XA3GLq0vsQfLoTG_-ffCrsURyofzogdB4BgXWu9MVAbCST-2HlgcC5gGzo0uo--pCNXgfWddIzIq1SSlrb1xvligluj5wwevNWLJnuGCG0VgNQQ0XT5jcw",
#   "refresh_token": "531ed8a7-2012-4d58-aecc-b03ae1acec31",
#   "token_type": "Bearer",
#   "expires_in": 3600,
#   "id_token": "eyJraWQiOiJiYWFzLWFsZmEtdGVzdC1qd3QiLCJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiIzNjRiODNjZS03NjJiLTQ3OWEtODdmNS1hZjgyYTY4NGFhZTYiLCJhdWQiOiIwNmZhYmQzNy0xOWU4LTRkMTItYjEzZC1lZmRlMDdjNGIwYWMiLCJhY3IiOiIyZmE6bG9naW46c21zIiwiYXpwIjoiMDZmYWJkMzctMTllOC00ZDEyLWIxM2QtZWZkZTA3YzRiMGFjIiwiYW1yIjpbImZhY2UiLCJwaW4iLCJzd2siLCJzbXMiLCJtZmEiLCJtY2EiLCJmcHQiLCJwd2QiXSwiYXV0aF90aW1lIjoxNTAzNDk5MTg1LCJpc3MiOiJodHRwczovL2lkLXNhbmRib3guYWxmYWJhbmsucnUvb2lkYyIsImV4cCI6MTcxMDUzODI1NCwiaWF0IjoxNzEwNTM0NjU0fQ.ouOdcx4aC1kXtIZy5ZMuFLDmOw-f7JfwYQFHOWTIn44yvggvyNiLXWHsD1Ao7L8SxRLYr_B2RXWz6QcWL8S3cjMaCi9ia6DgIBBALnoaI3PPn8IwmTwbDUtfPwQduyWZMMC76kSxSABVV-AAQamIGv0IcaOZDhr9uItZCwgOMo8Pj3rnSJk-FpMmH8rr_QFfWCUL8LK0R0jc0IkngPGHDMNGNE34d7ixP_8D8N7UIaUDKe0ixN6W6-O6byuBlpukn7OYtDj-zMc4Q6ac5LzO-i6O_5z7AxkhPgjngMGGHYz1yy6RqF73Bs8yORFRXRx3h1eJiuE1ZooPMdW_lcydsA"
# }


{
  "access_token": "eyJraWQiOiJiYWFzLWFsZmEtdGVzdC1qd3QiLCJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiIzNjRiODNjZS03NjJiLTQ3OWEtODdmNS1hZjgyYTY4NGFhZTYiLCJhdWQiOiJkYTk2NjFkZS0yZDMwLTQzZTQtYjQ3OC0zYzgwMTMwYTY4ZTUiLCJpc3MiOiJodHRwczovL2lkLXNhbmRib3guYWxmYWJhbmsucnUvb2lkYyIsImV4cCI6MTcxMzM4MDI0OCwic2NvcGVfc2VydmljZXMiOlsidHJhbnNhY3Rpb25zIl0sImlhdCI6MTcxMzM3NjY0OCwianRpIjoiYTM3MzdmMTYtMGUyNS00Mzc3LTkwNTMtZjcyMTE1ZDlkZTA5Iiwic2NvcGVfY2xhaW1zIjpbImV4cCIsInN1YiIsImFjciIsImF1ZCIsIm5vbmNlIiwiYXV0aF90aW1lIiwiYXpwIiwiaXNzIiwiaWF0Il19.3isVloPtwJykP0IOwJIF0VmfkZVou0_lbt2e9G37GbdWpkswN5o000UOlCGpzHZzsbMWyziwRZsF-l7j-Z40tvndZ7tEZFtE62wCjt0CgQ3nX0arRC_dJyh6HKo6NavnIoCGD-vszAz1AgdP74xqAXXUQRsLcruJoaI3xL6TolZU64UHr4xCv5P4crfPINMJOopzdraCce6FYv8fep-eklvw7vlAVyniVXrmF4sHCIg3bl6GNv5ULgZfNrGoWuqlptFMIpqRSQ8wPTAL6HR0t__5qjQTCtdrwSdFx_v3fYNGdGZrGWatkORBPxFw7_cH5th_oGuja71INNkpKJ1QIg",
  "refresh_token": "f88462f0-9b6a-43ed-92f4-41210cc3fef4",
  "token_type": "Bearer",
  "expires_in": 3600,
  "id_token": "eyJraWQiOiJiYWFzLWFsZmEtdGVzdC1qd3QiLCJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiIzNjRiODNjZS03NjJiLTQ3OWEtODdmNS1hZjgyYTY4NGFhZTYiLCJhdWQiOiJkYTk2NjFkZS0yZDMwLTQzZTQtYjQ3OC0zYzgwMTMwYTY4ZTUiLCJhY3IiOiIyZmE6bG9naW46c21zIiwiYXpwIjoiZGE5NjYxZGUtMmQzMC00M2U0LWI0NzgtM2M4MDEzMGE2OGU1IiwiYW1yIjpbImZhY2UiLCJwaW4iLCJzd2siLCJzbXMiLCJtZmEiLCJtY2EiLCJmcHQiLCJwd2QiXSwiYXV0aF90aW1lIjoxNzEzMzc2NjIxLCJpc3MiOiJodHRwczovL2lkLXNhbmRib3guYWxmYWJhbmsucnUvb2lkYyIsImV4cCI6MTcxMzM4MDIyMywiaWF0IjoxNzEzMzc2NjIzfQ.CH-pUEm6auuIpiQv1wUnM-WsyPLR0ZSCiT50fqR-bki-gEQf49iy044FWBetdY_lJt7UkxZoroqdvyba9XbyeEymPrAAyk2qS69o_Uq4dUsxhwU925r_nlLdawuRDp3ubZxRAKQuRQXnQh3GyYhVOzxRD9O9bdslZw_rBO0WtJxzbauHzWw3AwYfCLgKMYKigUHgUkKRh5tB0EWqzlZPs8TY2Y1z3Z6khUk__Wqlj6NSBpMG3r4cDV6TYjT5SfWJq0JnVI3eY0up6d48bN4ivDmAyL-uDTzrn2eP7uEpd3kI5AlV6hY5Oe9pBjqxBctNGugjj32WhxNre9SG6GVtAA"
}