arbat_transform:
  target: postgres
  outputs:
    postgres:
      type: postgres
      threads: 4
      host: "{{ env_var('DBT_POSTGRES_HOST') }}"
      port: "{{ env_var('DBT_POSTGRES_PORT') }}"
      user: "{{ env_var('DBT_POSTGRES_USER') }}"
      pass: "{{ env_var('DBT_POSTGRES_PASS') }}"
      dbname: "{{ env_var('DBT_POSTGRES_DBNAME') }}"
      schema: public